### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by alexol91** [collerek/ormar#1014]
When my application throws an exception and I try to access an endpoint again, it returns the error "(2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')".

It is as if it were not connected to the database or as if it did not refresh. Using SQLAlchemist I edited the parameters "pool_timeout=60, pool_recycle=280, pool_size=20, max_overflow=50" when I call create_engine, but in ORMAR I don't know how to do it.

Any idea how to do it?

Thanks!

**Comment by collerek** [comment]
Hi, ormar is using databses to run the queries so connection options go into databases instance you define and pass to models https://www.encode.io/databases/connections_and_transactions/#connection-options
