### ISSUE TITLE
How to get a list of rooms and users who are in that room by user id

### ISSUE THREAD

**Issue by valeXeich** [collerek/ormar#1081]
### Discussed in https://github.com/collerek/ormar/discussions/1080

<div type='discussions-op-text'>

<sup>Originally posted by **valeXeich** May  8, 2023</sup>
How to get a room by user who is in it and together with the room get all users who are in the room?

I make this request, but I get only one user and the one whose id I entered, but I want to get a room with all users who are in it

```python
await Room.objects.select_related('users').filter(users__id=1).all()
```

And this is what I get

[Room({'id': 1, 'messages': [], 'users': [User({'id': 1, 'username': 'alex', 'avatar': 'media/default/avatar', 'bio': None, 'password': '$2b$12$RR9X/eR2YJ2kPCVJjFi89uYxxkskj5IUBXR4iRKNSyEe3AYt1soX.', 'messages': [], 'rooms': [<weakproxy at 0x000001A1CB759440 to Room at 0x000001A1CB7265F0>], 'roomuser': RoomUser({'id': 2, 'user': None, 'room': None})})], 'roommessage': None, 'roomuser': None})]

But with this query I get

```python
await Room.objects.select_related('users').filter(users__id=2).all()
```

[Room({'id': 1, 'messages': [], 'users': [User({'id': 2, 'username': 'john', 'avatar': 'media/default/avatar', 'bio': None, 'password': '$2b$12$RR9X/eR2YJ2kPCVJjFi89uYxxkskj5IUBXR4iRKNSyEe3AYt1soX.', 'messages': [], 'rooms': [<weakproxy at 0x000001A1CB759440 to Room at 0x000001A1CB7265F0>], 'roomuser': RoomUser({'id': 1, 'user': None, 'room': None})})], 'roommessage': None, 'roomuser': None})]

And if you remove the filter, I get all users in a room, but I need to get only rooms where there is a user with a specific id and to show all users in that room, not just the one whose id I entered in the filter.

```python
await Room.objects.select_related('users').all()
```

[Room({'id': 1, 'messages': [], 'users': [User({'id': 1, 'username': 'alex', 'avatar': 'media/default/avatar', 'bio': None, 'password': '$2b$12$RR9X/eR2YJ2kPCVJjFi89uYxxkskj5IUBXR4iRKNSyEe3AYt1soX.', 'messages': [], 'rooms': [<weakproxy at 0x0000029972E89580 to Room at 0x0000029972E84C20>], 'roomuser': RoomUser({'id': 2, 'user': None, 'room': None})}), User({'id': 2, 'username': 'john', 'avatar': 'media/default/avatar', 'bio': None, 'password': '$2b$12$6n7aEXIYlkU2KGUvOeTCQeOfLMyL.PYUemS.DX8mqBnr0erZEblJC', 'messages': [], 'rooms': [<weakproxy at 0x0000029972E89A80 to NoneType at 0x00007FFEA36B7CC8>], 'roomuser': RoomUser({'id': 1, 'user': None, 'room': None})})], 'roommessage': None, 'roomuser': None})]

As you can see I only get one user whose id I entered but why? How can I get all users in the room?

My models: 

```python
class User(ormar.Model):
    class Meta(BaseMeta):
        tablename = 'users'
    
    id: int = ormar.Integer(primary_key=True)
    username: str = ormar.String(max_length=50, unique=True)
    avatar: str = ormar.Text(default='media/default/avatar')
    bio: str = ormar.String(max_length=70, nullable=True)
    password: str = ormar.String(max_length=250)


class Message(ormar.Model):
    class Meta(BaseMeta):
        tablename = 'messages'
    
    id: int = ormar.Integer(primary_key=True)
    file: str = ormar.Text(nullable=True)
    file_name: str = ormar.String(max_length=255, nullable=True)
    content: str = ormar.Text(nullable=True)
    is_file: bool = ormar.Boolean(default=False)
    readed: bool = ormar.Boolean(default=False)
    file_type: str = ormar.String(max_length=30, nullable=True)
    user: Optional[User] = ormar.ForeignKey(User)
    created_at: datetime.datetime = ormar.DateTime(
        default=datetime.datetime.utcnow
    )
    updated_at: datetime.datetime = ormar.DateTime(
        default=datetime.datetime.utcnow,
        server_default="now()"
    )


class Room(ormar.Model):
    class Meta(BaseMeta):
        tablename = 'rooms'
    
    id: int = ormar.Integer(primary_key=True)
    messages: Optional[List[Message]] = ormar.ManyToMany(Message)
    users: Optional[List[User]] = ormar.ManyToMany(User)
```

</div>

**Comment by collerek** [comment]
Sorry for the late answer, you can use prefetch_related for this:

```python
check = await User.objects.prefetch_related("rooms__users").get(User.id == 1)
pprint.pp([{"room": x.id, "users": [z.username for z in x.users]} for x in check.rooms])

# will produce
[{'room': 1, 'users': ['user1', 'user2']},
 {'room': 2, 'users': ['user1', 'user3']},
 {'room': 3, 'users': ['user1']}]

# Note that it's extracted without dumping model to dict or json as it has cyclical reference so it will exclude
pprint.pp(check.model_dump())

# will produce
{'id': 1, 'username': 'user1', 'rooms': [{'id': 1}, {'id': 2}, {'id': 3}]}
```
