### ISSUE TITLE
Encrypt the data stored in the database 

### ISSUE THREAD

**Issue by schaulet** [collerek/ormar#110]
It would be very usefull to have to possibility to encrypt the data stored in the database in an easy way.
I'm working on a project with legal constraints and privacy law. 
I don't want to encrypt/decrypt in my functional code. It's a technical constraint with should be manage on the ORM (or in the database or in the two). You can see the discussion here: #109.

A good solution (developper point of view) would be parameters in the declaration of the field like this:
```
class User(ormar.Model):
    class Meta:
        tablename: str = "users"

    id: int = ormar.Integer(primary_key=True, index=True)
    email: str = ormar.String(max_length=255, nullable=False)
    password: str = ormar.String(max_length=255, nullable=False, crypt_method="hash")
    first_name: str = ormar.String(max_length=255, nullable=False)
    last_name: str = ormar.String(max_length=255, nullable=False)
    category: str = ormar.String(max_length=255, nullable=True)
   social_security_number: str = ormar.String(max_length=13, nullable=False, crypt_method="fernet", crypt_key="mySuperSecuredKey")
```
parameters could be:
```
  crypt_method: str # for selecting one of the default method provided
  crypt_key: str # provide key to be use with encrypt_method
  crypt_custom_encrypt: func # a method provided by developper to encrypt data as a parameter
  crypt_custom_decrypt: func # a method provided by developper to decrypt data as a parameter
```
crypt_custom_encrypt could be an alias of a more generic parameter: apply_func_on_write
crypt_custom_decrypt could be an alias of a more generic parameter: apply_func_on_read
By this way we could imagine applying every type of work per field we need.

As alternative to column encryption, i searched on database side, but sounds not very clear on how it will be interface with alembic for exemple.
SQLAlchemy has a similar feature: EncryptedType

Thanks for your good job and reactivity.

**Comment by schaulet** [comment]
I have just made some modification to provide a parameter apply_func for string.
It is working for basic get and save. I'm not sure of the impact with prefetch.
I never made PR for now. So how can i share modification i made ?

**Comment by collerek** [comment]
As for the changes you should fork this repo and commit your changes to your copy (to new branch preferably) and create a pull request from your copy of `ormar` to this repo.

As for the Encryption the parameters should probably be introduced in `BaseField` class and read from `kwargs` dictionary as all of them are optional. Base on those params the database column definition should be swapped from the original `sqlalchemy` type (like `Integer`) to this newly created `EncryptedField` type based on `String`, that handles the actual encryption. It's similar to what is done with `JSON` field, where a special `sqlalchemy.Column` type was created. 

That way it's the `sqlalchemy` that handles the encryption\decrypton part as it has to be done in many places but only during actual db save\read. So it should not be handled in `ormar` methods as you would have to edit `save\update` on `Model` but also `create\update\bulk_create\bulk_update` etc. on `QuerySet`. With a new `sqlalchemy.Column` type it's gonna be handled there (and you can even base your code on `sqlalchemy_utils`).
