### ISSUE TITLE
How to query condition_1 or condition_2 ?

### ISSUE THREAD

**Issue by zhonghai9967** [collerek/ormar#116]
for condition_1  "and"  condition_2":
p= await Book.objects.filter(title=None , author='').first()

but,The following sentence is wrong:
p= await Book.objects.filter(title=None **or** author='').first()

**Comment by collerek** [comment]
Yeah there is no way to do this now, will add this as I already though about this limitation before but right now I work on #74 as it's quite big (and in the meantime I have quite a lot of refactors that's why I need to finish it first)

**Comment by collerek** [comment]
You don't need this anymore?

**Comment by zhonghai9967** [comment]
I really need this function!
If you can achieve it, that's great!

**Comment by pylakey** [comment]
Totally agree with the author of this issue.
We all look forward to meet this feature in the next update ☺️

**Comment by hramtsov** [comment]
we are very much waiting for you!

**Comment by collerek** [comment]
It's gonna be in a next release -> actually it's done already but now it complicates limit/offset queries which I need to rework and every backend has it different way 😕

**Comment by collerek** [comment]
Added in 0.9.7 please update and check the docs.
