### ISSUE TITLE
Please support pydantic-2.x

### ISSUE THREAD

**Issue by yurivict** [collerek/ormar#1243]
**Describe the bug**

PYPI now has pydantic at 2.x and having two versions of Pydantic at the same time causes conflicts in resolving dependencies for some other packages, because pydantic-1.x and pydantic-2.x use the same namespace 'pydantic'.

**Comment by saltysteev** [comment]
This repository hasn't had an actual commit in 5 months I would suggest to migrate to another library

**Comment by collerek** [comment]
See my comment in https://github.com/collerek/ormar/issues/1236

**Comment by collerek** [comment]
You can try version 0.20.0
