### ISSUE TITLE
v0.20.0 is released as stable instead of beta

### ISSUE THREAD

**Issue by slavovthinks** [collerek/ormar#1293]
**Describe the bug**
Im migrating to ormar and I was trying to run the examples from the docs but I was getting `AttributeError: 'ModelMetaclass' object has no attribute 'ormar_config'` as well as `AttributeError: 'MyModel' object has no attribute 'ormar_config'`. I was unable to figure out what is the problem so I tried lowering the version of ormar which fixed the issue.

I went to GH and I saw that v.0.20.0 was released as a stable version instead of beta.

**To Reproduce**
1.` pip install ormar` or `pip install --upgrade ormar`

**Comment by AlexCAPS** [comment]
Try to define you model like this

```python
class Example(ormar.Model):
    ormar_config = base_ormar_config.copy(tablename="example")
    ...
    # other fields
```

**Comment by kokroo** [comment]
Yeah this should definitely be in the beta channel.

**Comment by collerek** [comment]
Hmm I thought it was released as beta, at least that's what I checked during creating of the release, will  try to check it out tomorrow

**Comment by collerek** [comment]
the 0.20.1 is now released as normal release
