### ISSUE TITLE
Specify a different field to select relations into

### ISSUE THREAD

**Issue by smock** [collerek/ormar#1304]
**Is your feature request related to a problem? Please describe.**
I'd like to have type consistency on fields corresponding to foreign keys.  Currently I can sometimes expect an object with just its primary key filled, or an object corresponding to the related object, depending on if I have selected the related model.  This can make it difficult to reason about the data in downstream functions.

**Describe the solution you'd like**
I'd like to be able to define virtual ForeignKey relationships on directly related columns.  For example, defining:
chart_id: int = ormar.Integer(nullable=False)
chart: Optional[Chart] = ormar.ForeignKey(Chart, name='chart_id', virtual=True)

would create a foreign key constraint on chart_id, and define a new field for the related object called 'chart'.

Then, when querying the model, if I were to call Model.objects.select_related('chart').get_or_none(), I'd expect to have both 'chart_id' and 'chart' available to me.

**Comment by collerek** [comment]
That can be simply achieved with name of the FK and property

```python
import asyncio
from typing import Optional

import databases
import ormar
import sqlalchemy

database = databases.Database("sqlite:///db.sqlite")
metadata = sqlalchemy.MetaData()

config = ormar.OrmarConfig(
        database=database,
        metadata=metadata,
    )


class Chart(ormar.Model):
    ormar_config = config.copy()

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=200)


class Dashboard(ormar.Model):
    ormar_config = config.copy()

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=200)
    chart: Optional[Chart] = ormar.ForeignKey(Chart, name="chart_id")

    @property
    def chart_id(self):
        return self.chart.pk


config.engine = sqlalchemy.create_engine(config.database.url._url)
config.metadata.create_all(config.engine)


async def check():
    chart = await Chart.objects.create(name="chart 1")
    dash = await Dashboard.objects.create(name="dash1", chart=chart)
    assert dash.chart.name == "chart 1"
    assert dash.chart_id == chart.pk


asyncio.run(check())

config.metadata.drop_all(config.engine)
```

Related model will be loaded into chart, in db it will be chart_id and chart_id is a property on model too.
