### ISSUE TITLE
`load_all` from `QuerySet`

### ISSUE THREAD

**Issue by Erhannis** [collerek/ormar#131]
**Is your feature request related to a problem? Please describe.**
When trying to load a list of objects, e.g. as `Thing.objects.all()`, or `thing.others.all()`, if you want to load the objects recursively, you currently need to call `load_all(follow=true)` on them in a loop.

**Describe the solution you'd like**
It would be more convenient (and likely efficient) if you could call `load_all` directly on a `QuerySet` (and `QuerysetProxy`).

**Describe alternatives you've considered**
`load_all` in a loop.  It works, it's just a little tedious, and makes multiple database calls.

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

**Comment by collerek** [comment]
Added in 0.10.0
