### ISSUE TITLE
Syntax error in built SQL query on Postgres

### ISSUE THREAD

**Issue by aliakhtar** [collerek/ormar#133]
**Describe the bug**
On Postgres, if I have a model called User, and I do:

User.objects.get(foo=bar)

The generated SQL expression will cause a syntax error from Postgres:

`syntax error at or near "."`

The reason is, in the generated expression, we are quote escaping the table name everywhere except in the very last 'Order by' statement. I.e we get:

SELECT "user".id AS id
FROM "user"
WHERE "user".foo = 'bar' ORDER BY user.id

Not having the table name in quotes in the order by statement causes the syntax error in postgres

Is there a workaround available for now @collerek ?

**To Reproduce**
- Setup a postgres app
- Create a simple User table and model
- Run the query `User.objects.get(foo=bar)`

**Expected behavior**
Data is returned as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/5325112/112162452-e2a72380-8c0d-11eb-85e6-90ff2ef73d23.png)

**Versions (please complete the following information):**
 - Database backend used (mysql/sqlite/postgress) postgres 12.6
 - Python version 3.9.2
 - `ormar` version 0.10.0
 - `pydantic` version 1.8
 - if applicable `fastapi` version 0.63.0

**Additional context**

**Comment by collerek** [comment]
Can you post some code to reproduce (especially your user model definition)?

**Comment by aliakhtar** [comment]
@collerek Here's the user model and the code I'm using to query: https://gist.github.com/aliakhtar/2807a0a305cdab2f0db9f20190b4b4f1

**Comment by aliakhtar** [comment]
However even just the query ```SELECT "user".id AS id
FROM "user"
WHERE "user".foo = 'bar' ORDER BY user.id``` returns that syntax error - but quote escaping the table name in order by fixing it.

**Comment by aliakhtar** [comment]
@collerek Is there a way to have no `order_by` statement added to certain queries?

**Comment by collerek** [comment]
@aliakhtar right now - no. 

The easiest way to get this issue away is change the tablename to non reserved sql keyword (as this is the source of the error), i.e. 'users' instead of 'users'.

**Comment by aliakhtar** [comment]
Thank you - changing to `users` worked in this case. But I'll leave the issue open since it does escape the table name everywhere else - so it should do the same in the order by.

**Comment by collerek** [comment]
Fixed in 0.10.1
