### ISSUE TITLE
Adding the same item twice to a RelationProxy corrupts the _relation_cache

### ISSUE THREAD

**Issue by camillol** [collerek/ormar#1335]
**Describe the bug**
As the title says. I saw this with an `ormar.ManyToMany`. The underlying list did not grow in length, but the cache entry was updated with `new_idx = len(self)`, thereby pointing past the end of the list. This then caused an `IndexError` later on during `_clean_items_on_load`.

**Comment by collerek** [comment]
Should be fixed in #1346 

That will no longer raise IndexErrors, note that you still can insert the same models into the db multiple times, so to really prevent duplicated entries you should add an unique constraint on the explicitly declared `Through` model.
