### ISSUE TITLE
Request ormar to support pydantic 2.6, 2.7, ...

### ISSUE THREAD

**Issue by brunorpinho** [collerek/ormar#1387]
Hi @collerek ,

Just want to check if it's possible for us to support higher pydantic versions or is there a reason ormar is fixed at 2.5?

BTW, thank you for this amazing tool.

**Comment by Zerorigin** [comment]
[fastapi-jwt-auth3](https://github.com/tistaharahap/fastapi-jwt-auth3) need：`pydantic==2.7.3`
[ormar](https://github.com/collerek/ormar) need：`pydantic==2.5.3` for ormar[postgresql]

This makes it impossible to use both wheels in the same project.

**Comment by brunorpinho** [comment]
Hi @Zerorigin, thank you for taking action on this issue.

Sorry, I could not understand the issue as `fastapi-jwt-auth3` does not seem to be a problem.

What do you mean by `ormar need：pydantic==2.5.3 for ormar==0.20.1` ?

It seems that ormar and fastapi-jwt-auth3 can be used in the same project if ormar allows higher versions than 2.5.3.

**Comment by Zerorigin** [comment]
> It seems that ormar and fastapi-jwt-auth3 can be used in the same project if ormar allows higher versions than 2.5.3.

Yeap.

**Comment by collerek** [comment]
Pin bumped in #1388 will release soon
