### ISSUE TITLE
Ormar and pydantic-settings incompatibility

### ISSUE THREAD

**Issue by markjrouse** [collerek/ormar#1396]
**Describe the bug**
Can't install pydantic-settings if ormar is installed due to incompatibility issues.

"Because no versions of pydantic-settings match >2.5.2,<3.0.0
 and pydantic-settings (2.5.2) depends on pydantic (>=2.7.0), pydantic-settings (>=2.5.2,<3.0.0) requires pydantic (>=2.7.0).
And because ormar (0.20.1) depends on pydantic (v2.5.3)
 and no versions of ormar match >0.20.1,<0.21.0, pydantic-settings (>=2.5.2,<3.0.0) is incompatible with ormar (>=0.20.1,<0.21.0).
So, because reason-capdis depends on both ormar (^0.20.1) and pydantic-settings (^2.5.2), version solving failed."

**To Reproduce**
1. poetry add ormar
2. poetry add pydantic-settings

(Note: this should be a complete and concise piece of code that allows reproduction of an issue)

**Expected behavior**
I should be able to add both ormar and pydantic-settings

**Versions (please complete the following information):**
 - Database backend used (postgress)
 - Python 3.11
 - `ormar` 0.20.1
 - `pydantic` 2.5.2
 - if applicable `fastapi` ^0.111.0

**Comment by ariel-frischer** [comment]
Running into a similar issue looking for ormar to support pydantic >=2.8.2

**Comment by collerek** [comment]
Pin bumped in #1388 will release soon
