### ISSUE TITLE
Update sqlalchemy to support >=1.4

### ISSUE THREAD

**Issue by collerek** [collerek/ormar#142]
After databases merge their solution and stop blocking the update: https://github.com/encode/databases/pull/299

**Comment by johnthagen** [comment]
Would the fact that `sqlalchemy` [1.4 has native `async` support](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html) bring any improvements?

**Comment by collerek** [comment]
Immediately - no - since all queries are run through `encode/databases`. 

This issue is rather to not block bumping version of `sqlalchemy` if you use it in other then `ormar` places, and I need to adjust `ormar` as version >= 1.4 has some breaking changes even without `async` support.

But looking at how `encode/databases` is half-abandoned in the long run I will probably switch fully to `sqlalchemy`, but that is a bigger refactor and since `async` support is still in alpha version in `sqlalchemy` (I'm also not very fond of the async API but I need to dig deeper) I'm waiting to see how the situation will develop.

**Comment by collerek** [comment]
Added in 0.10.17 (#325)
