### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by begyy** [collerek/ormar#143]
- Database backend used (postgress)
 - Python 3.8
 - `ormar` 0.9.9
 - `pydantic` version

![image](https://user-images.githubusercontent.com/44405438/113709762-519b7680-96fc-11eb-822b-dc5cb259d1c5.png)
![image](https://user-images.githubusercontent.com/44405438/113709781-595b1b00-96fc-11eb-8429-6392d31c7095.png)

**Comment by collerek** [comment]
Can you update to 0.10.2 just released and check again? (I fixed one recursion error there)

If after update it still persists can you also post `BaseModel` definition and `BaseMeta`? 
Preferably as code not as picture :)

**Comment by begyy** [comment]
everything is working :)
