### ISSUE TITLE
add support for native pydantic fields

### ISSUE THREAD

**Issue by avico78** [collerek/ormar#160]
following documentation ormar supports 12 pydantic fields:
https://collerek.github.io/ormar/fields/field-types/

What is the consideration for not supporting all (or at least much more) fields which supported by pydantic ?
is there way adding pydatnic field manually to ormat model (not as non DB field).
In example -  I need for PaymentCardNumber ,URL ,EmailStr and Json

_Originally posted by @avico78 in https://github.com/collerek/ormar/discussions/159_

**Comment by collerek** [comment]
Added in #183
