### ISSUE TITLE
Add a LargeBinary/Blob field

### ISSUE THREAD

**Issue by johnthagen** [collerek/ormar#166]
## **Is your feature request related to a problem? Please describe.**

We are trying to port a codebase that uses a [SQLite Blob field](https://docs.python.org/3/library/sqlite3.html#introduction) to `ormar`.

- This is modeled as `bytes` within Python.

- SQLAlchemy calls this a [`LargeBinary` field](https://docs.sqlalchemy.org/en/14/core/type_basics.html#sqlalchemy.types.LargeBinary).

- `peewee` calls this a [`BlobField`](http://docs.peewee-orm.com/en/latest/peewee/models.html#field-types-table).

## **Describe the solution you'd like**

Be able to declare a model like:

```py
class File(ormar.Model):
    data: bytes = ormar.LargeBinary()
```

And have `sqlalchemy` / Pydantic support like other fields.

**Comment by collerek** [comment]
Sure, sounds like a good idea ;)

**Comment by johnthagen** [comment]
@collerek Anything I can help with with this issue? I think this is last milestone needed to take `ormar` into production for us. :)

**Comment by collerek** [comment]
Ok, it's done will be in next release.

**Comment by johnthagen** [comment]
Thanks! I will be sure to test it out after its released and let you know if I hit any issues.

**Comment by collerek** [comment]
Added in #183
