### ISSUE TITLE
Support for Pydantic 1.8.2

### ISSUE THREAD

**Issue by mawoka-myblock** [collerek/ormar#205]
I think, thats everything.

**Comment by collerek** [comment]
Yep, i got it in the pipeline, and hope to get it soon especially that older versions has minor security flaw. Need to check the compatibility / adjust ormar as ormar is using also internals of the pydantic, so theoretically non-breaking changes can be breaking for ormar.

**Comment by mawoka-myblock** [comment]
Nice! Thank you for your fast reply!

**Comment by collerek** [comment]
Added in 0.10.9 (#210)

**Comment by mawoka-myblock** [comment]
Thanks!
