### ISSUE TITLE
Record is imported even if not using PostgreSQL

### ISSUE THREAD

**Issue by HarrySky** [collerek/ormar#23]
Currently in model.py Record is imported without checks in place whether user even have `asyncpg` installed:
https://github.com/collerek/ormar/blob/250f55ad6888bd9adefa4aef6e413087d3771d9a/ormar/models/model.py#L5

It causes my app that use SQLite to crash with `ModuleNotFoundError: No module named 'asyncpg'`

One possible solution is to wrap it in `try-except ModuleNotFoundError` block, another - refactor check in `Model.extract_prefixed_table_columns`. Your thoughts?

It seems that tests are running with all backends and those kind of errors are not catched

**Comment by collerek** [comment]
Should be fixed in #24.
Please update to last version and check.

**Comment by HarrySky** [comment]
Yes, fixed, thanks a lot for quick patch :smile:

I am experiencing other problems, will open issues in a moment
