### ISSUE TITLE
Proper annotations

### ISSUE THREAD

**Issue by HarrySky** [collerek/ormar#25]
Right now **mypy**, **pyright** and other static type analyzers are screaming from annotations like this: `id: Integer(primary_key=True)`

mypy error:
```
lmat/db/models.py:33: error: Invalid type comment or annotation  [valid-type]
lmat/db/models.py:33: note: Suggestion: use Integer[...] instead of Integer(...)
```

pyright error:
```
Expected class type but received "Integer" Pyright (reportGeneralTypeIssues)
```

Why `id = Integer(primary_key=True)` syntax is not used (like in `orm`)? I guess it is because of the way you extract annotations, do you consider changing the approach? I would like to use this library in one project, but it is unusable in this state (I cannot just put `# type: ignore[valid-type]` on every line in models)

Can help with this when I have some spare time, unfortunately I am forced to go back to `orm`.

**Comment by collerek** [comment]
It is like this because that's how pydantic define fields (as class variables with annotation and possibly a default value), and I am subclassing pydantic.BaseField. Was already digging into pydantic internals and I believe (not sure now) that just writing my own annotation based on fields definition would not be enough. There is a lot of "magic" happening both in fastapi and pydantic (cloning/subclassing of models, using built in pydantic functions that I cannot modify etc.) Orm is using encode/typesystem not pydantic, but cannot be used with fastapi in place of pydantic models.

As for ignoring you can always set mypy.ini file and provide:
```
[mypy-<path.to.files.with.ormar.models>]
ignore_errors = True
```
but I guess this is not something you want in a long run 😆 

Will check what can be done about this.

**Comment by collerek** [comment]
Should be fixed in #28 - update to 0.4.0 and check

**Comment by HarrySky** [comment]
Will check in the nearest future :rocket: Thanks a lot :tada:

**Comment by HarrySky** [comment]
Great, new way of annotating fields works :smile:

Had a problem, though, `ormar.String` expects `max_length`, not `length` as stated in docs: `name: str = ormar.String(length=100)`.

**Comment by collerek** [comment]
@HarrySky, yeah previously it was `length` but `pydantic` accepts `max_length` - tried to update this to adjust but maybe some were missed ;D Will try to update it again next deploy.

**Comment by zdytch** [comment]
Suffering from this right now. In VSCode I have Pylance type checking on. It is based on Pyright and Mypy.

So when I don't use annotation, like this:
`size = ormar.Integer(minimum=0, default=0)`
no screaming

But, when I add annotation:
`size: int = ormar.Integer(minimum=0, default=0)`
i get the error:
```
Expression of type "BaseField" cannot be assigned to declared type "int"
  "BaseField" is incompatible with "int" 
```

Adding `# type: ignore` to the file top of the file or to separate line hides the error

**Comment by collerek** [comment]
That's weird, whole codebase including the tests is checked with mypy and it passes, so I assume it comes from pyright. Will check what I can do about it.

**Comment by collerek** [comment]
Sorry for late answer, will try to tackle this one in the nearest future. Any help welcomed! 😊

**Comment by ajlive** [comment]
<img src="https://user-images.githubusercontent.com/1761517/171983596-b87ee78c-845a-43d3-80fb-0ca6c994da0e.png" height=200>

Gets me every time

**Comment by davidolrik** [comment]
> That's weird, whole codebase including the tests is checked with mypy and it passes, so I assume it comes from pyright. Will check what I can do about it.

You are correct - it is an error from pyright (Which is what Pylance is using underneath)

The weird thing is that I don't see the error when opening the Ormar source in vscode, but I do get the error in my own project.

This small snippet in `pyproject.toml` suppresses the error for me:

```toml
[tool.pyright]
reportGeneralTypeIssues = false
```

**Comment by vekkuli** [comment]
I would love to see this solved as well. Any other workarounds you can think of other than explicit `cast` or the aforementioned disabling `reportGeneralTypeIssues`?
