### ISSUE TITLE
error when i tried to install with postgresql support

### ISSUE THREAD

**Issue by jeasoft** [collerek/ormar#255]
Disclaimer: Maybe this is not a **real bug**, but just in case

I was trying to install ormar with postgresql support as is described in the docs:
`pip install 'ormar[postgresql]'`

This resulted in this error:

```
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.

```

This is because don't have postgresql installed in my machine, and I know, but why not use psycopg2-binary instead of just psycopg2? If we want to try ormar with docker or with a remote PostgreSQL server we don't have to compile this package. In fact, when you install asyncpg by yourself pip just download the executable object and you don't have to compile the package on your own. 

My suggestion is just to update the setup dependencies from `psycopg2` to `psycopg2-binary`.

**Versions (please complete the following information):**
 - Database backend used (postgresql)
 - Python version: 3.9.5
 - `ormar` version: 0.10.13
 - `pydantic` version: 1.8.2
 

Again, great just with this

**Comment by collerek** [comment]
Fixed in 0.10.14 (via #265).
