### ISSUE TITLE
Filter: SQL NOT IN

### ISSUE THREAD

**Issue by pawamoy** [collerek/ormar#272]
**Is your feature request related to a problem? Please describe.**
I need to delete all rows of a table that do not match a set of IDs. It seems that it is currently not possible natively, and I have to proceed in two (or more steps): select the whole table, filter out IDs at the application level (using Python), and delete the kept items one by one, or run a second query to select the kept IDs and delete them in one-go.

**Describe the solution you'd like**
I would like a way to filter using NOT IN:

```python
old_dependencies = ProjectDependency.objects.filter(id__not_in=new_dependencies_ids)
await old_dependencies.delete()
```

**Describe alternatives you've considered**
See alternative solution mentioned above. It needs at least two queries instead of one.

---

I also want to thank you: this package is absolutely great! It makes things so, so easy! I love it 🚀! Thanks a lot for developing and maintaining it 🙂

**Comment by collerek** [comment]
You should be able to use `exclude` instead of `filter`, this reverts the condition.
https://collerek.github.io/ormar/queries/filter-and-sort/#exclude

```python
old_dependencies = ProjectDependency.objects.exclude(id__in=new_dependencies_ids).all()
```

Thanks for the nice words about the package - it grew much bigger than I initially thought :)

**Comment by pawamoy** [comment]
Damn, I did think there would be some "reversed" way of doing things, but failed to remember exclude, I'm dumb 😂 Thank you for your help!
