### ISSUE TITLE
PostgreSQL Array Columns

### ISSUE THREAD

**Issue by Lester1989** [collerek/ormar#273]
I really like the Postgres feature of having array type columns.
sqlAlchemy supports the PostgreSQL dialect refer:
https://docs.sqlalchemy.org/en/14/dialects/postgresql.html?highlight=array#sqlalchemy.dialects.postgresql.ARRAY
 
It would be nice to use them with ormar like:
`characteristics:list[str] = ormar.Array(element_type='String')`
or something like that.

Until that is possible I will use JSON() but it seems to be an overkill

Considering the DRY Principle, this package is the way to go when using a Database for an API. Thank you for that

**Comment by rajaiswal** [comment]
@collerek I believe this is now implemented in [v2.1.0](https://github.com/tophat/ormar-postgres-extensions/releases/tag/v2.1.0). Should we mark this as closed?

**Comment by collerek** [comment]
@rajaiswal Indeed we should close this, thanks for remainder :)

**Comment by mohanedomanos** [comment]
@collerek Hi, as ormar-postgres-extension is no longer supported by the latest version of ormar, is there any other solution or library to help support the Array column type?
