### ISSUE TITLE
warning Message is no f-String

### ISSUE THREAD

**Issue by Lester1989** [collerek/ormar#274]
I receive the message:
`WARNING:root:Table {table_name} had no fields so auto Integer primary key named id created.`
where table_name is not filled in.

This can be corrected in:
ormar-master\ormar\models\helpers\sqlalchemy.py
line 155: `"Table {table_name} had no fields so auto "`
should be `f"Table {new_model.Meta.tablename} had no fields so auto "`

(update: inserted correct fix, since table_name is not a known field

**Comment by collerek** [comment]
Thanks for catching that )

**Comment by collerek** [comment]
Fixed by #280
