### ISSUE TITLE
pydantic.error_wrappers.ValidationError: n validation errors for model_name

### ISSUE THREAD

**Issue by Mng-dev-ai** [collerek/ormar#294]
I'm trying to create a category which has manytomany field with sport model 
```
# models
class Sport(ormar.Model):
    """
    Database model for sport partner fields
    """
    id = ormar.Integer(primary_key=True)
    # other fields
    
    class Meta:
        tablename = "sports"
        metadata = metadata
        database = database

class Category(ormar.Model):
    """
    Categories to be used in a partner
    """
    id = ormar.Integer(primary_key=True)
    # other fields
    sport = ormar.ManyToMany(Sport)
    
    class Meta:
        tablename = "categories"
        metadata = metadata
        database = database

# schema
class CategoryIn(pydantic.BaseModel):
    class Config:
        orm_mode = True

    # fields
    sport: List[int]

# routes
@app.post("/categories/", response_model=Category)
async def create_category(category: CategoryIn):
    return await Category(**category.dict()).save()

```
and when i try to add new category i get  pydantic.error_wrappers.ValidationError: n validation errors for Category

**Comment by collerek** [comment]
And what is the exact exception message and what you are trying to pass in a payload?

**Comment by Mng-dev-ai** [comment]
I trying to pass the ids of sport like that 
```
{
  "name": "string",
  "sport": [
    1,
    2
  ]
}
```
and the exact exception is 
response -> field 1 in sport model
  field required (type=value_error.missing)
response -> field 2 in sport model
  field required (type=value_error.missing)
response -> field 3 in sport model
  field required (type=value_error.missing)

**Comment by collerek** [comment]
What are your library versions (fastapi, ormar and pydantic) as I cannot reproduce this error?

Few points:
 - You don't need an `in` pydantic model if you want to pass values of foreign keys -> ormar allows also passing values like this
 - You pass a name in payload but your models don't have it (so it's ignored)
 - By default when you call `save` only the main model is saved, not the related ones, so the sports are not saved in your case
 - If you want to pass those ids to relation use `add` method on M2M relation, but that requires you to save the sports before as the related models on m2m have to exists (be saved) before adding to the relation
 - If you want to save also sports in one go read about `save_related` shortcut method, but that won't work if you are passing your primary key manually as ormar will think those already exist and try to update them and not save (you can pass a model without pk to create it)
