### ISSUE TITLE
Weird behavior when trying to set ForeignKey relation to None

### ISSUE THREAD

**Issue by soderluk** [collerek/ormar#301]
**Describe the bug**
I have a model A where one relation `b` is `ForeignKey` to another model B. Saving model A with the relation, all is good, the related model's ID is stored in the database.

Now, I DON'T want to delete the related model, but I want to unset the relation from model A, by updating model A and setting the relation to `None`.

I would guess, that by doing so, having the following definition:

```python
b: Optional[B] = ormar.ForeignKey(B, nullable=True)
``` 
and running `await model_a.update(b=None)` it would set the relation to null in the database, but it doesn't. For some reason updating a ForeignKey relation with None doesn't set it to null in the database.
 

**To Reproduce**
```python
from typing import List, Optional

import ormar
import pytest

from app.db.database import db, engine, metadata


class B(ormar.Model):
    class Meta:
        metadata = metadata
        database = db
        tablename = "b"

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=50)


class A(ormar.Model):
    class Meta:
        metadata = metadata
        database = db
        tablename = "a"

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=255)
    b: Optional[B] = ormar.ForeignKey(B, nullable=True)


@pytest.mark.asyncio
@pytest.mark.parametrize("id_", [1, 2, 3, 4, 5])
async def test_create_bs(id_):
    await B.objects.create(name=f"B {id_}")


@pytest.mark.asyncio
@pytest.mark.parametrize("id_", [1, 2, 3, 4, 5])
async def test_create_primary_models(id_):
    await A(name=f"A {id_}").save()


@pytest.mark.asyncio
async def test_update_a():
    b1: B = await B.objects.get(pk=1)
    a1: A = await A.objects.get(pk=1)

    await a1.update(b=b1)
    await a1.load_all(True)

    assert a1.b.name == "B 1"

    await a1.update(b=None)
    await a1.load_all(True)

    assert a1.b is None


@pytest.fixture(autouse=True, scope="module")
def create_test_database():
    metadata.create_all(engine)
    yield
    metadata.drop_all(engine)

```

**Expected behavior**
My expectation is that `assert a1.b is None` passes, since I set the relation `b` to `None`. 

Or is there something I'm missing right now?

**Versions (please complete the following information):**
 - Database backend used: sqlite
 - Python version: 3.8.10
 - `ormar` version: 0.10.16
 - `pydantic` version: 1.8.2
 - if applicable `fastapi` version: 0.65.3

**Additional context**

**Comment by collerek** [comment]
That was actually by design :)

That won't work with M2M as well as with reverse relations and I wanted to have a consistent API to avoid confusion and questions, as well as prevent accidental overwrites. You cannot also set `a1.b = None` <- this will not remove the relation.

So to nullify the relation you actually need to explicitly call `remove` for all relations types.

```python
@pytest.mark.asyncio
async def test_update_a():
    await B(name='B 1', id=1).save()
    await A(name='A 1', id=1).save()
    b1: B = await B.objects.get(pk=1)
    a1: A = await A.objects.get(pk=1)

    await a1.update(b=b1)
    await a1.load_all(True)

    assert a1.b.name == "B 1"

    a1.remove(a1.b, name='b') # child and relation name
    await a1.update()
    await a1.load_all(True)
```

**Comment by soderluk** [comment]
@collerek: Ah, I thought the `remove` will actually delete the record from the related table. Well, that was my bad then :) Closing this one.

**Comment by collerek** [comment]
There is a keep_related flag that you can control what happens for reverse relationship and m2m. For fk the model stays (as the one with fk column is "the child")
