### ISSUE TITLE
Add Non Unique Multicolumn Indices

### ISSUE THREAD

**Issue by tobymao** [collerek/ormar#307]
**Is your feature request related to a problem? Please describe.**
I would like to be able to define a multicolumn index but currently only UniqueConstraints are possible.

https://github.com/collerek/ormar/discussions/304

**Describe the solution you'd like**
A way to do this without using sqlalchemy core.

**Describe alternatives you've considered**
Using     constraints = [

        
          sqlalchemy.Index('idx_a_b', 'a', 'b')

    ]

Achievese this

**Additional context**

**Comment by collerek** [comment]
Added in #346
