### ISSUE TITLE
Allow server_default nullable: False to be optional in Pydnatic

### ISSUE THREAD

**Issue by tobymao** [collerek/ormar#308]
**Is your feature request related to a problem? Please describe.**
When using server_default and nullable: False, the Pydantic model still requires this field even though it will be filled in by the server.

**Describe the solution you'd like**
There should be a way to allow this.

**Describe alternatives you've considered**

**Additional context**

**Comment by tobymao** [comment]
It's because ormar is conflating what 'nullable' means. I want nullable: False to apply at the database level. I want the DB to enforce that the column X cannot be null. But from the pydantic side, I never want to pass it in because i want to use the server_default.

**Comment by collerek** [comment]
That is true - ormar combines those settings, but from the point of orm the conflicting options doesn't make sense:
- there is no point in having an orm model that you cannot ever save (null field in pydantic and not nullable db field)
- there is no point in having a nullable field if you always provide a value (required field in pydantic, and nullable column in db).

With fail early approach (zen of python :) )  the ormar/pydantic should be matching what you set on the database side.

When you provide a `server_default` parameter (that will be used only when you pass None for a given column/field) then your ddl schema will be modified to reflect this https://docs.sqlalchemy.org/en/14/core/defaults.html#server-invoked-ddl-explicit-default-expressions. 

Now I know that what you request might be useful, probably a separate argument that by default takes the nullable parameter value but you can explicitly overwrite it.

As a workaround till then you can hack server_default functionality, that simply inserts the corresponding value into the ddl.

So if you construct you model like this:

```python
class Song(ormar.Model):
    class Meta:
        tablename = "songs"
        metadata = metadata
        database = database

    id: int = ormar.Integer(primary_key=True)
    name: str = ormar.String(max_length=100, nullable=True, server_default=text("CURRENT_TIMESTAMP NOT NULL"))
    sort_order: int = ormar.Integer()
```

the corresponding ddl looks like this:

```sql
CREATE TABLE songs (
	id INTEGER NOT NULL, 
	name VARCHAR(100) DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	sort_order INTEGER NOT NULL, 
	PRIMARY KEY (id)
)
```

Note that `nullable` is explicitly set to `True` but column is still created as `NOT NULL`.

**Comment by maslyankov** [comment]
I have this model:
```
class Entry(Model):
    class Meta(BaseMeta):
        tablename = f'{DB_LEGACY_PREFIX}entry'

    id: int = Integer(primary_key=True)
    start_time: int = Integer(nullable=False, index=True, server_default=text("'0'"), comment='Unix timestamp')
    end_time: int = Integer(nullable=False, index=True, server_default=text("'0'"), comment='Unix timestamp')
    entry_type: int = Integer(nullable=False, server_default=text("'0'"))
    created_on: datetime = DateTime(name="timestamp",
                                    server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    created_by: str = String(name="create_by", max_length=80, nullable=False, server_default=text("''"))
    modified_by: str = String(max_length=80, nullable=False, server_default=text("''"))
    name: str = String(max_length=80, nullable=False, server_default=text("''"))
    type: str = String(max_length=1, nullable=False, server_default=text("'E'"))
    description: str = String(max_length=1000, nullable=True)
    status: int = SmallInteger(nullable=False, server_default=text("'0'"))
```

and when I try to send request with body:
```
{
  "id": 0,
  "start_time": 1631028000,
  "end_time": 1631031600,
  "entry_type": 0,
  "name": "This is my test",
  "type": "M",
  "description": "Testttt",
  "status": 0,
}
```

I get validation errors:
```
{
  "detail": [
    {
      "loc": [
        "body",
        "created_by"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "modified_by"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}```

Why is this happening? I am using MySQL as a DB.

**Comment by collerek** [comment]
That's exactly what this issue is about.

Right now the same settings change both the SQL column as well as the pydantic field, so when you set nullable=False it means the column becomes not null and the pydantic field becomes required.

I will add `sql_nulable` argument that will allow overwriting this setting for the database column.

**Comment by maslyankov** [comment]
Thank you a bunch!! Any ETA or workaround?

> That's exactly what this issue is about.
> 
> Right now the same settings change both the SQL column as well as the pydantic field, so when you set nullable=False it means the column becomes not null and the pydantic field becomes required.
> 
> I will add `sql_nulable` argument that will allow overwriting this setting for the database column.

Thank you a bunch!! Any ETA or workaround?

**Comment by collerek** [comment]
This is already done, pushed to branch add_index, waiting for some clarification on 2 more issues to check if I can fix them quickly before the next release.

**Comment by collerek** [comment]
Added in #346
