### ISSUE TITLE
Add ability to override default Pydantic model used by Ormar field

### ISSUE THREAD

**Issue by franzwollang** [collerek/ormar#311]
At the moment, each Ormar field defaults to a specific Pydantic model. However, very often I want a more specific/constrained Pydantic model to enforce a particular schema. Examples:

- `Ormar.Integer` uses `int` and `Ormar.Float` uses `float`; I want to enforce non-negativity using `Pydantic.PositiveInteger` and `Pydantic.PositiveFloat` but Ormar ignores type hints and doesn't offer an option to modify the Pydantic model used by the field.
- `Ormar.Text` or `Ormar.String` both use `str`, but I want to use RegEx to enforce a particular pattern using `Pydantic.constr`.
- `Ormar.JSON` uses `Pydantic.Json` but no further constraints can be added in the usual manner (i.e. `foo: Json[List[str, int]]` or `bar: Json[Pydantic.conlist(min_items = 1, max_items = 5)]`).

I could add a work around by adding specific validators for each field to enforce the constraints I want, but it seems like unnecessary bloat since Pydantic offers these common use cases already built-in.

Is there a way to simply add a kwarg to Ormar fields that allows the user to override the Pydantic model used? I think it would be fine to make doing this be at the user's own risk; if they add an override but don't make sure it's compatible with the associated SQLAlchemy type, that's on them.

I think there is a strong case for adding this feature since the current situation negatively affects the usability of Pydantic.

**Comment by franzwollang** [comment]
Wait, I immediately regret adding this issue. I jumped the gun here. There are definitely plenty of kwarg options already supported that one can use to replicate most of the desired behavior. My bad!

**Comment by collerek** [comment]
:)

Yeah, it changed in pydantic at some point so not all of them are supported but the most useful ones should be there.
You can pass those that populate the Field in pydantic: https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation
