### ISSUE TITLE
Improve support for constraints on the JSON field type

### ISSUE THREAD

**Issue by franzwollang** [collerek/ormar#312]
I would like to be able to add constraints to the Pydantic model associated with the `Ormar.JSON` field type.

I am using JSON fields to store data that I don't need any indexing or explicit relationships on, like simple lists and objects, but I still would like to be able to enforce certain constraints on them. For instance, something like these is possible with regular Pydantic:

- `image_links: Json[conlist(CustomURLFormat, min_items = 1, max_items = 3)]`
- `custom_tags: Json[Dict[str, conset(str, max_items = 10)]`

I could work around this limitation by defining custom validators as needed, but Pydantic already supports nice types for this sort of thing, as shown above. I don't know whether it would make the most sense to add new kwargs to the `Ormar.JSON` type for a selected subset of possibilities or to simply allow the user to add a custom Pydantic model as an override.

I originally created a new issue that was too broad and overlapped with already existing features (#311), and then realized my mistake and immediately closed it. I hope this one is more pertinent.

**Comment by franzwollang** [comment]
On second thought, custom models as overrides would be preferable to a limited set of kwargs. I realize I'm also storing address objects and configuration objects that have properties that are themselves various constrained types or occasionally have an extra level of list/dict nesting.

It doesn't seem likely that this type of expressiveness could be achieved with a fixed set of options.

**Comment by collerek** [comment]
In theory, it should be easy as each field defines the type to be used under `_type` variable.

Although there are special cases (like JSON field - that needs to be loaded/dumped) so in order for `ormar` to work you need to provide a subclass of the proper type (in this case subclass of Pydantic.Json). You can check currently used types in `ormar/fields/model_fields.py`)

You can check this probably by defining your own subclass.

You can test it like this:

```python
from ormar import JSON

class ConstraintJSON(JSON):
    _type = pydantic.Json[Dict[str, conset(str, max_items = 10)]
```

Let me know if that works.

**Comment by collerek** [comment]
Added in 0.10.17 (#325)

**Comment by franzwollang** [comment]
> 
> 
> Added in 0.10.17 (#325)

Thanks a bunch for this! This adds a lot of flexibility.
