### ISSUE TITLE
Make Ormar compatible with Pydantic .construct() method or implement Ormar equivalent

### ISSUE THREAD

**Issue by franzwollang** [collerek/ormar#318]
### Discussed in https://github.com/collerek/ormar/discussions/317

<div type='discussions-op-text'>

<sup>Originally posted by **franzwollang** August 22, 2021</sup>
In Pydantic, one can use the .construct() method to instantiate a model while skipping validation. I tried it out with an Ormar model and it seemed to work, except there were some random exceptions when I tried to .save() it that gave me the impression that perhaps doing this broke some of Ormar's internals.

Does Ormar work with the .construct() method? Or is there an Ormar equivalent?</div>

**Comment by franzwollang** [comment]
**Is your feature request related to a problem? Please describe.**
Pydantic has a class method that allows one to skip validation. Skipping validation can very useful for speeding up certain types of operations, like retrieving large amounts of data from a trusted source or using models to generate data for testing purpose. The Pydantic documentation claims the difference can be as much as 30X faster.

**Describe the solution you'd like**
For Ormar to be compatible with Pydantic's .construct() class method or to implement an Ormar native equivalent.

**Describe alternatives you've considered**
I vaguely recall there is something somewhere in the Ormar documentation that mentions validation can be skipped in a very specific situation, but I would have to very carefully comb through the documentation again and then see what the context of it was. I don't think it was intended as a general purpose option for skipping validation though.

**Additional context**
Pydantic documentation:
https://pydantic-docs.helpmanual.io/usage/models/#creating-models-without-validation

Potentially helpful threads on the Pydantic repo related to this topic:
https://github.com/samuelcolvin/pydantic/issues/897
https://github.com/samuelcolvin/pydantic/issues/1168
https://github.com/samuelcolvin/pydantic/issues/1212

**Comment by collerek** [comment]
Ok, I checked the links that you provided (thanks) and the code of `construct` in the pydantic model.

It seems that for the sake of speed this does not support nested models, how would you like it to work for `ormar`?

**Comment by franzwollang** [comment]
Thanks for asking!

I agree with many of the posters in the threads above, nested models is a very common use case; one of the core functionalities of an ORM is in the name, that of representing each table schema as a model and providing tools that make managing the models and their connections easier. So it would be very nice if it were supported here.

I don't think recursive models need to be supported (i.e. their could be a stopping criterion when hitting the same model again), but nested models definitely should be if possible.

**Comment by franzwollang** [comment]
SQLAlchemy supports recursion/cycles but deals with it by limiting the depth of the recursion. I'm not sure how they implement it, though, so I don't know if they keep track of the root model and count how many times the same model is encountered along the current active path in the graph or what.

Because I don't know exactly how it's implemented, I don't know what difficulties might lie in getting SQLAlchemy to play nice.

**Comment by collerek** [comment]
Ormar build a relation map which is kind of a tree that is checking reoccurring models on same paths and breaks there. It's used to load all/ save all/ dict/ json etc. So this one can be done with the same. 

So including nested models basically means that i have to skip the original construct and overwrite it.

**Comment by franzwollang** [comment]
I guess it depends on what the "original construct" method is. If you are just initializing Pydantic models (calling the models or using the __init__ method directly), then you would just have to substitute those calls for calls to the .construct() method on the models instead. That's a very simple substitution.
