### ISSUE TITLE
[Bug] No way to give unique constants a name so they get named as None

### ISSUE THREAD

**Issue by maslyankov** [collerek/ormar#336]
**Describe the bug**
No way to give unique constants a name so they get named as None

**To Reproduce**
Add a field like this:
 `name: str = String(name="room_name", unique=True, max_length=25, nullable=False)`

(Note: this should be a complete and concise piece of code that allows reproduction of an issue)

**Expected behavior**

**Screenshots**
Here is output from alembic:
`INFO  [alembic.autogenerate.compare] Detected added unique constraint 'None' on '['room_name']'`

**Versions (please complete the following information):**
 - Database backend used (mysql/sqlite/postgress) -> MySQL
 - Python version -> 3.9.6
 - `ormar` version -> 0.10.18
 - `pydantic` version -> 1.8.2
 - if applicable `fastapi` version ->  0.68.1
- alembic version ->  1.7.1

**Additional context**
This behavior seems to happen only for some columns and only when I have an existing db and tables to do migrations on top of. When I delete all tables and do an init migration revision, it does not generate unique constants with None.

**Comment by collerek** [comment]
Hi,

It's working according to sqlalchemy core specification: https://docs.sqlalchemy.org/en/14/core/constraints.html#unique-constraint

When you set `unique` directly on a column there is no way to set the constraint name in `sqlalchemy`.

If you want to set a name you have to explicitly specify `UniqueConstraint`, which in `ormar` you can do by specifying `UniqueColumns` in `Meta.constraints` (https://collerek.github.io/ormar/models/#constraints). 

Note that `ormar` provide names for all `UniqueColumns` constraints automatically, so you don't have to do this.
