### ISSUE TITLE
Creating records directly in tests in a FastAPI appliction

### ISSUE THREAD

**Issue by dbatten5** [collerek/ormar#419]
**Describe the bug**
Suppose I have an endpoint like this:
```python
@router.get("/", response_model=List[Item])
async def get_items(keys: List[str] = Query([])) -> List[Item]:
    return await Item.objects.filter(key__in=keys).all()
```

I'd like to test this with something like:
```python
@pytest.mark.asyncio
async def test_success(self, client: TestClient) -> None:
    item_1 = await Item.objects.create(key="1")
    item_2 = await Item.objects.create(key="2")

    url = router.url_path_for("get_items")

    response = client.get(
        f"{url}?keys=1&keys=2&keys=3",
    )

    data = response.json()

    assert len(data) == 2
    assert data[0]["id"] == item_1.id
    assert data[1]["id"] == item_2.id
```

However, running this i get errors of this nature:

```
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
```

I'm using the following fixtures:

```python
@pytest.fixture(autouse=True, scope="class")
def create_test_database() -> Generator[None, None, None]:
    """Create a test database before tests and tear down afterwards."""
    engine = sqlalchemy.create_engine(settings.sqlalchemy_database_uri)
    metadata.create_all(engine)
    yield
    metadata.drop_all(engine)


@pytest.fixture(scope="module")
def client() -> Generator[TestClient, None, None]:
    """Initialize a `TestClient` to be used in tests.

    Yields:
        the test client
    """
    with TestClient(app) as test_client:
        yield test_client
```

Is there a way around this? I notice in your tests you create dummy routes for the test client app to create objects in the tests, is that the only way to create these factory style records in tests?

**To Reproduce**

This is a little tricky given that it relies on a postgres database but I can give a full example if needs be

**Expected behavior**
I should be able to create a record in test

**Screenshots**

**Versions (please complete the following information):**
 - Database backend used (mysql/sqlite/postgress): postgres:13
 - Python version: 3.9.0
 - `ormar` version: 0.10.22
 - `pydantic` version: 1.8.2
 - if applicable `fastapi` version: 0.70.0

**Comment by collerek** [comment]
You didn't show this but if `TestClient` is the one from `starlette` it's sync only, so you cannot use it in async marked tests.
You have to switch to `httpx` or something like this and actually await the client call to the endpoint.

I create the data creation endpoints for two reasons: 
1. It's exactly this one as I didn't want to introduce an additional async client for requests
2. I want to test also create functionality with `fastapi` as some bugs reveal only in this setup

**Comment by dbatten5** [comment]
ahh makes total sense, thanks for your quick response. will look to switch to `httpx`
