### ISSUE TITLE
Many-to-many fields have strange types

### ISSUE THREAD

**Issue by dbatten5** [collerek/ormar#435]
**Describe the bug**
Consider the following contrived example:

```python
class Actor(ormar.Model):
    class Meta(MainMeta):
        pass

    id = ormar.Integer(primary_key=True)
    name = ormar.String(max_length=255)

class Film(ormar.Model):
    class Meta(MainMeta):
        pass

    id = ormar.Integer(primary_key=True)
    cast = ormar.ManyToMany(to=Actor, skip_reverse=True)
```

I would expect the type of `film.cast` to be `List[Actor]`, however, inspecting `Film.schema()` it looks like it has type `Union[int, Actor, List[Actor]]`:

```python
>>> Film.schema()
>>> {'title': 'Film',
 'description': 'Schema for the `Film` model.',
 'type': 'object',
 'properties': {'id': {'title': 'Id',
   'type': 'integer'},
  'cast': {'title': 'Cast',
   'anyOf': [{'type': 'integer'},
    {'$ref': '#/definitions/Actor'},
    {'type': 'array', 'items': {'$ref': '#/definitions/Actor'}}]}},
 ...
```

Note that if I cast to a `pydantic` model it appears the field has the correct type:
```python
>>> PydanticFilm = Film.get_pydantic()
>>> PydanticFilm.schema()
>>> {'title': 'Film_FNN',
 'type': 'object',
 'properties': {'id': {'title': 'Id',
   'minimum': None,
   'maximum': None,
   'type': 'integer'},
  'cast': {'title': 'Cast',
   'type': 'array',
   'items': {'$ref': '#/definitions/Actor_IAY'}},
...
```
This is causing issues with the OpenAPI schema generated by FastAPI with ormar

**Expected behavior**
A many-to-many field should have the type `List[Relation]` (unless I'm missing something?)

**Versions (please complete the following information):**
 - Database backend used (mysql/sqlite/postgress): postgres
 - Python version: 3.9.0
 - `ormar` version: 0.10.22
 - `pydantic` version: 1.8.2
 - if applicable `fastapi` version: 0.70.0

**Comment by collerek** [comment]
This is an intended behavior. Ormar accepts payloads of primary key value (int in your case), single child model (Actor) or list of related models (List[Actor]). Remember that types are the same for returning a result and setting a value, that's why all relation fields accept union of all possible types, otherwise the validation would fail.

**Comment by dbatten5** [comment]
Ah ok that makes perfect sense, thank you. So in this case what would be the best way to handle autogeneration of my OpenAPI schema? Define a new pydantic model and use that as the response model? I tried using `response_model=Film.get_pydantic()` but then, [as mentioned in the docs](https://collerek.github.io/ormar/models/methods/#get_pydantic) three random letters are added to the class name (and any nested classes), which would then show up in the openAPI json as such

**Comment by collerek** [comment]
Yes if you don't want the 3 letters in name you can either rename the class __name__ (should work) or manually create the pydantic model.
