### ISSUE TITLE
Allow filtering by column names and python operators

### ISSUE THREAD

**Issue by collerek** [collerek/ormar#51]
Support not only current django like dunder separated names filtering:

```python
albums = Album.objects.filter(tracks__order__gte=2).all()
```

But also something more like sqlalchemy:
```python
albums = Album.objects.filter(Album.tracks.order >= 2).all()
```

**Comment by pylakey** [comment]
Just want to say that it would be a very good feature 💪 I really like how it is implemented in peewee library (for example % operaror is used as a shortcut for sql LIKE)

**Comment by myusko** [comment]
@collerek Does someone working on the issue? I'll happy to investigate and send a draft PR.

P.S It won't be quick PR, since I've some load at my work =\

**Comment by collerek** [comment]
@myusko No, right now no one is working on this issue. I'm working on set of small fixes, enhancements and bug fixes right now. Any PR welcome, if you have time 😉

**Comment by collerek** [comment]
Ok, now I'm working on this and it's gonna be in next release :)

**Comment by collerek** [comment]
Added in 0.10.4
