### ISSUE TITLE
UUIDs cannot be queried using get as primary key

### ISSUE THREAD

**Issue by hidaris** [collerek/ormar#57]
Recently, I started using ormar instead of tortoise-orm in my projects, but have encountered a strange problem, if I use uuid as the primary key of a model, I can't match the data when using get query.

example:
```python
class MainMeta(ormar.ModelMeta):
    metadata = metadata
    database = database


class UserModel(ormar.Model):

    class Meta(MainMeta):
        tablename = "usermodel"

    id: ormar.UUID(primary_key=True)
    username = ormar.String(index=True, unique=True, null=False, max_length=255)
    email = ormar.String(index=True, unique=True, nullable=False, max_length=255)
    hashed_password = ormar.String(null=False, max_length=255)
    is_active = ormar.Boolean(default=True, nullable=False)
    is_superuser = ormar.Boolean(default=False, nullable=False)

user = await UserModel.objects.first()
await UserModel.objects.get(id=user.id) # raise NoMatch
await UserModel.objects.get(username=user.username) # Match user
```

**Comment by collerek** [comment]
Hi,

UUID field has no default as there are different types.

The most common i uuid4 I would say but not exclusive.

But the fix is easy just provide a default function and pass uuid like:

```python
import uuid
id: uuid.UUID = ormar.UUID(primary_key=True, default=uuid.uuid4)
```

**Comment by hidaris** [comment]
The addition of a default value for uuid4 did not take effect, the data came from an existing db and was not created via ormar. However, it can be confirmed that the id of the old data is uuid4
```python
class BaseUser(CreateUpdateDictModel):
    """Base User model."""

    id: Optional[UUID4] = None
    email: Optional[EmailStr] = None
    is_active: Optional[bool] = True
    is_superuser: Optional[bool] = False

    @validator("id", pre=True, always=True)
    def default_id(cls, v):
        return v or uuid.uuid4()

```
Is there more information that I can provide to help locate the problem?

**Comment by collerek** [comment]
Ok, so there is a database with a field already.
I need info what type of the field is in DB (I think only postgres support special uuid but might remember wrong).
Since you moved from tortoise I assume you use postgres, so that I don't have to ask :)

**Comment by hidaris** [comment]
@collerek Currently using sqlite, not postgre

**Comment by collerek** [comment]
Oh right I confused with gino :) So what is the db field type? Varchar(?)

**Comment by hidaris** [comment]
![Screenshot from 2020-11-28 03-20-18](https://user-images.githubusercontent.com/8336146/100479289-b8929880-3128-11eb-891f-e74d1670aa4b.png)
This is the table structure corresponding to the usermodel

**Comment by hidaris** [comment]
Sorry, it's the middle of the night in my time zone, it's too late for me to go to bed, I'll check back in the morning to see if it's a problem with my usage.

**Comment by collerek** [comment]
Don't worry same here (currently Lao - 3 AM :) ). WIll also check it later - might be some weird handling of uuid fields in compiling filters for sqlalchemy.

**Comment by collerek** [comment]
OK, so ormar is by default saving UUID in hex format in CHAR(32) field without the dashes.

So I added the parameter `uuid_format` for UUID field that can be:
*  hex (default) -> like it was CHAR(32) - no dashes
*  string -> CHAR(36) with dashes.

to change to string set it to 'string':
```python
id: uuid.UUID = ormar.UUID(primary_key=True, default=uuid.uuid4, uuid_format='string')
```

Sample:
   *  hex value = c616ab438cce49dbbf4380d109251dce
   *  string value = c616ab43-8cce-49db-bf43-80d109251dce

Please update to version 0.5.4 for this feature.

**Comment by hidaris** [comment]
Problem solved, thank you for such a quick response and fix!
