### ISSUE TITLE
Declaring specific class as response_model in FastAPI produces RecursionError

### ISSUE THREAD

**Issue by mawoka-myblock** [collerek/ormar#580]
**Describe the bug**
I get a RecursionError if the `Quiz` from below is set as the `response_model` in a FasAPI route-decorator.

```python
from uuid import uuid4 as uuid
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Json
from . import metadata, database
import ormar

class User(ormar.Model):
    """
    The user model
    """
    id: uuid = ormar.UUID(primary_key=True, default=uuid)
    email: str = ormar.String(unique=True, max_length=100)
    username: str = ormar.String(unique=True, max_length=100)
    password: str = ormar.String(unique=True, max_length=100)
    verified: bool = ormar.Boolean(default=False)
    verify_key: str = ormar.String(unique=True, max_length=100, nullable=True)
    created_at: datetime = ormar.DateTime(default=datetime.now())

    class Meta:
        tablename = 'users'
        metadata = metadata
        database = database


class UserSession(ormar.Model):
    """
    The user session model
    """
    id: uuid = ormar.UUID(primary_key=True, default=uuid)
    user: uuid = ormar.ForeignKey(User)
    session_key: str = ormar.String(unique=True, max_length=64)
    created_at: datetime = ormar.DateTime(default=datetime.now())

    class Meta:
        tablename = 'user_sessions'
        metadata = metadata
        database = database
class QuizAnswer(BaseModel):
    right: bool
    answer: str


class QuizQuestion(BaseModel):
    question: str
    answers: list[QuizAnswer]


class QuizInput(BaseModel):
    title: str
    description: str
    questions: list[QuizQuestion]


class Quiz(ormar.Model):
    id: uuid = ormar.UUID(primary_key=True, default=uuid)
    title: str = ormar.String(max_length=100)
    description: str = ormar.String(max_length=300, nullable=True)
    created_at: datetime = ormar.DateTime(default=datetime.now())
    updated_at: datetime = ormar.DateTime(default=datetime.now())
    user_id: uuid = ormar.UUID(foreign_key=User.id)
    questions: Json[list[QuizQuestion]] = ormar.JSON(nullable=False)

    class Meta:
        tablename = 'quiz'
        metadata = metadata
        database = database
```
Like this:
```python
from fastapi import APIRouter
router = APIRouter()

The example **doesn't** run "as is"

@router.post("/create", response_model=Quiz)
async def create_quiz_lol(quiz_input: QuizInput):
    quiz = Quiz(**quiz_input.dict(), user_id=user.id)
    return await quiz.save()
```

**Versions (please complete the following information):**
 - Database backend used (mysql/sqlite/postgress)
 - Python 3.10.2
 - `ormar` 0.10.25
 - `pydantic` 1.9.0
 - `FastAPI` 0.74.1

**Comment by collerek** [comment]
Can you check with an older release i.e. 0.10.24? Want to know if this is something new

**Comment by mawoka-myblock** [comment]
> Can you check with an older release i.e. 0.10.24? Want to know if this is something new

It also occurs on 0.10.24. Thank you for the fast response!

**Comment by collerek** [comment]
Thanks for checking, can you also post a sample payload you are using to call this API endpoint, will be easier to test. See that you are using python 3.10 which is not yet fully supported, which database and driver are you using?

**Comment by mawoka-myblock** [comment]
I am using sqlite (`aiosqlite` 0.17.0)

```json
{
   "public":false,
   "title":"Some test question",
   "description":"A description",
   "questions":[
      {
         "question":"Is ClassQuiz cool?",
         "answers":[
            {
               "right":true,
               "answer":"Yes"
            },
            {
               "right":false,
               "answer":"No"
            }
         ]
      },
      {
         "question":"Do you like open source?",
         "answers":[
            {
               "right":true,
               "answer":"Yes"
            },
            {
               "right":false,
               "answer":"No"
            },
            {
               "right":false,
               "answer":"Maybe"
            }
         ]
      }
   ]
}
```

**Comment by mciszczon** [comment]
Hmmm, from what I've seen, if you set `response_model`, then you should return this model from the view? When I set a `response_model` to be a model inheriting from `pydantic.BaseModal`, and then returned this model from the view, the payload would be transformed twice: once by me in the view, and then again by the model provided in `response_model`?

**Comment by mawoka-myblock** [comment]
> Hmmm, from what I've seen, if you set `response_model`, then you should not return this model instance from the view? When I set a `response_model` to be a model inheriting from `pydantic.BaseModel`, and then returned this model from the view, the payload would be transformed twice: once by me in the view, and then again by the model provided in `response_model`?

I don't know, but it displays the return model in the openapi schema, so that's enough for me.

**Comment by collerek** [comment]
Fixed in 0.11.0 - please update and check.

**Comment by mawoka-myblock** [comment]
> Fixed in 0.11.0 - please update and check.

Yes, the RecursionError is gone, but now, I get the following `ValueError`:
```python
ValueError: [TypeError("'ModelField' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

**Comment by collerek** [comment]
Can you provide some code behind this? Cause i used your code for a test case that passes so need something more to reproduce.

**Comment by mawoka-myblock** [comment]
> Can you provide some code behind this? Cause i used your code for a test case that passes so need something more to reproduce.

Oh, I should have added that this error only occurs if you try to access the `/openapi.json`-route.
