### ISSUE TITLE
Is there a plan to support model inheritance?

### ISSUE THREAD

**Issue by hidaris** [collerek/ormar#67]
If model inheritance is supported, we can save a lot of repetitive work by leveraging from inheritance.
At the same time, it can be better integrated with the existing ecosystem. Such as [fastapi-users](https://github.com/frankie567/fastapi-users/blob/master/fastapi_users/db/tortoise.py#L11).

**Comment by collerek** [comment]
Hi,

In general - yes :)

Depending on which type of inheritance you want it might be sooner or later, as it's a different effort and level of complication of the code.

Out of the inheritance types:
* **Mixins** - don't even subclass `ormar.Model`, just define fields that are later used on several different models (like `created_date` and `updated_date` on each model), only actual models create tables but those fields from mixins are added
* **Concrete table inheritance** - means that parent is marked as abstract and each child has it's own table with columns from parent and own child columns, kind of similar to Mixins but parent also is a Model
* **Single table inheritance** - means that only one table is created with fields that are combination/sum of the parent and all children models but child models use only subset of column in db (all parent and own ones, skipping the other children ones)
* **Multi/ Joined table inheritance** - means that part of the columns is saved on parent model and part is saved on child model that are connected to each other by kind of one to one relation and under the hood you operate on two models at once
* **Proxy models** - means that only parent has an actual table, children just add methods, modify settings etc.

So which inheritance you have in mind? :)

**Comment by hidaris** [comment]
@collerek What I was expecting was Concrete table inheritance.

**Comment by collerek** [comment]
@hidaris ok, so Mixins and Concrete one (maybe also Proxy) are easiest to implement, so should appear in first order ;)

**Comment by collerek** [comment]
Mixins and Concrete table introduced in 0.8.0.
Will close it for now as other types of inheritance seems less important as of now.

Feel free to reopen if something does not work, or any other inheritance should be prioritized.

**Comment by hidaris** [comment]
Wow, thank you so much!
