### ISSUE TITLE
having trouble handling foreign keys with uuid

### ISSUE THREAD

**Issue by hidaris** [collerek/ormar#71]
I'm having trouble handling foreign keys with uuid, here is the definition of the model
```python
class User(ormar.Model):
    class Meta(MainMeta):
        tablename = "user"

    id: ormar.UUID(primary_key=True, default=uuid.uuid4, uuid_format='string')
    username = ormar.String(index=True, unique=True, null=False, max_length=255)
    email = ormar.String(index=True, unique=True, nullable=False, max_length=255)
    hashed_password = ormar.String(null=False, max_length=255)
    is_active = ormar.Boolean(default=True, nullable=False)
    is_superuser = ormar.Boolean(default=False, nullable=False)


class Token(ormar.Model):
    class Meta(MainMeta):
        tablename = "token"

    id = ormar.Integer(primary_key=True)
    text = ormar.String(max_length=4, unique=True)
    user = ormar.ForeignKey(User, related_name='tokens')
    created_at = ormar.DateTime(server_default=sqlalchemy.func.now())

    def __str__(self):
        return self.text
```
when i perform 
```python
await Token.objects.order_by('-created_at').limit(page_size).offset(page_size * (page_num - 1)).all()
```
raise

`RelationshipInstanceError: Relationship error - ForeignKey OrmarBaseUserModel is of type <class 'uuid.UUID'> while <class 'str'> passed as a parameter.
`

I looked at the source code [ormar/fields/foreign_key.py#L123](https://github.com/collerek/ormar/blob/5552a8297fc668d68cd150c70db1b12fdffeeebf/ormar/fields/foreign_key.py#L123) and it seems to be because the actual storage of uuid is string, but the judgment still uses uuid.

**Comment by collerek** [comment]
Hi, 

Yes, when a pk_only related model is constructed it was taking the raw db value (so str), but expected the actual type of uuid.

Should be fixed in 0.7.3, please update and check. :)

**Comment by hidaris** [comment]
Thank you very much, hope ormar gets better and better

**Comment by collerek** [comment]
You already help to make it happen, thanks! 😁
