### ISSUE TITLE
ormar requires aiosqlite

### ISSUE THREAD

**Issue by onerandomusername** [collerek/ormar#713]
**Describe the bug**
The aiosqlite dependency is always installed even if I don't want to use sqlite as my driver.

**To Reproduce**
1. Install the package with `pip install ormar`

(Note: this should be a complete and concise piece of code that allows reproduction of an issue)

**Expected behavior**
The aiosqlite driver is not installed, and is an optional dependency

**Actual behavior**
The aiosqlite driver is installed, even though I did not request it to be installed.

**Screenshots**

**Versions (please complete the following information):**
 - Database backend used: None.
 - Python version: 3.9
 - `ormar` version: 0.11.x
 - `pydantic` version: 1.9.1
 - if applicable `fastapi` version

**Additional context**

I did check that installing `pip install databases` does *not* install aiosqlite and that this is an ormar packaging issue.

**Comment by mawoka-myblock** [comment]
You can either install `aiosqlite` by hand or install ormar with the dependency directly: `pip install "ormar[sqlite]"`

**Comment by onerandomusername** [comment]
> You can either install `aiosqlite` by hand or install ormar with the dependency directly: `pip install "ormar[sqlite]"`

That's not my problem. My problem is that I *don't want* aiosqlite to be installed, and due to a packaging issue ormar always installs aiosqlite no matter if I provide extras or not.

**Comment by collerek** [comment]
Thanks for catching that - should be fixed in 0.11.2

**Comment by onerandomusername** [comment]
> Thanks for catching that - should be fixed in 0.11.2


I think this is a breaking change as users who installed 0.11.1 and belo without specifying aiosqlite will now not have aiosqlite installed, perhaps this should 0.12.0?

**Comment by collerek** [comment]
Yeah, I thought about the same for a while, but that's actually not a change but a bugfix, it was always described and intended to explicitly provide your driver as described in https://collerek.github.io/ormar/install/
