### ISSUE TITLE
ForeignKeyViolationError in CASCADE clear() method

### ISSUE THREAD

**Issue by SepehrBazyar** [collerek/ormar#724]
**Describe the bug:**
When I try to CASCADE delete relational models.

**To Reproduce:**
```python
# Models
import ormar
from uuid import UUID, uuid4

class A(ormar.Model):
    id: UUID = ormar.UUID(uuid_format="string", primary_key=True, default=uuid4)
    name: str = ormar.String(max_length=64, nullalbe=False)

class B(ormar.Model):
    id: UUID = ormar.UUID(uuid_format="string", primary_key=True, default=uuid4)
    name: str = ormar.String(max_length=64, nullalbe=False)
    a: A = ormar.ForeignKey(to=A)

class C(ormar.Model):
    id: UUID = ormar.UUID(uuid_format="string", primary_key=True, default=uuid4)
    name: str = ormar.String(max_length=64, nullalbe=False)
    b: B = ormar.ForeignKey(to=B)

# QuerySet
# (a is an object from A model class.)
>>> await a.bs.clear(keep_reversed=False)
~/Desktop/MyProject/venv/lib/python3.10/site-packages/asyncpg/protocol/protocol.pyx in bind_execute()

ForeignKeyViolationError: update or delete on table "bs" violates foreign key constraint "fk_cs_bs_id_b" on table "cs"
DETAIL:  Key (id)=(592c8bd6-6796-48d0-9158-fe1fcd0cfd57) is still referenced from table "cs".
```

**Versions:**
 - Database backend: PostgreSQL
 - Python version: 3.10.4
 - `ormar` version: 0.11.2
 - `pydantic` version: 1.9.0

**Comment by collerek** [comment]
That's kind of expected, isn't it?

You try to delete Bs' while there are Cs' that reference those Bs', hence the exception.
If you want to clear Cs' while you delete Bs' then use `ondelete="CASCADE"` in ForeignKey definition.

Remember that you operate only on A <-> B relation so `keep_reversed` relates only to the Bs'. But if anything else references the B and you didn't set cascades it will fail as in this example.

**Comment by SepehrBazyar** [comment]
> 



> That's kind of expected, isn't it?
> 
> You try to delete Bs' while there are Cs' that reference those Bs', hence the exception. If you want to clear Cs' while you delete Bs' then use `ondelete="CASCADE"` in ForeignKey definition.
> 
> Remember that you operate only on A <-> B relation so `keep_reversed` relates only to the Bs'. But if anything else references the B and you didn't set cascades it will fail as in this example.

Yes that's right; I realized. Thank you
I think the document of this part is incomplete because only the `to` and `related_name` arguments are described and the rest are not described.
If you agree and allow me to add the explanations of these items

Also, don't you think it's better to write an `Enum` class for `ondelete` and `onuodate` values?

**Comment by collerek** [comment]
That is true, didn't realize it's missing, thanks for pointing this out! :)

If you have time I would be more than happy to accept your contribution to documenting this :).

As for the enum - I'm all for it but that would be a breaking change. 
So let's introduce it gradually -> let's add an enum class for it and change the ForeignKey definition to accept both `str` and `enum`. Then, inside, check the value of `onupdate` and `ondelete` and if it's a string then parse it to enum and issue a deprecation warning.

How about that?

**Comment by SepehrBazyar** [comment]
> That is true, didn't realize it's missing, thanks for pointing this out! :)
> 
> If you have time I would be more than happy to accept your contribution to documenting this :).
> 
> As for the enum - I'm all for it but that would be a breaking change. So let's introduce it gradually -> let's add an enum class for it and change the ForeignKey definition to accept both `str` and `enum`. Then, inside, check the value of `onupdate` and `ondelete` and if it's a string then parse it to enum and issue a deprecation warning.
> 
> How about that?

Yes, I will definitely be very happy (:
It is absolutely true, I will implement it in the same way.
