### ISSUE TITLE
Limit QuerySet Results with Number 0

### ISSUE THREAD

**Issue by SepehrBazyar** [collerek/ormar#766]
**Describe the bug**
Not applying Zero(0) size `limit`.

**To Reproduce**
```python
>>> await User.objects.limit(0).all()
[User({}), ...]  # list of all users
```

**Expected behavior**
I expected an empty list to be returned.

**Versions:**
 - Database backend: PostgreSQL
 - Python version: 3.10.4
 - `ormar` version: 0.11.2
 - `pydantic`: 1.9.0

**Comment by SepehrBazyar** [comment]
> **Describe the bug** Not applying Zero(0) size `limit`.
> 
> **To Reproduce**
> 
> ```python
> >>> await User.objects.limit(0).all()
> [User({}), ...]  # list of all users
> ```
> 
> **Expected behavior** I expected an empty list to be returned.
> 
> **Versions:**
> 
> * Database backend: PostgreSQL
> * Python version: 3.10.4
> * `ormar` version: 0.11.2
> * `pydantic`: 1.9.0

I guess it doesn't apply because zero is boolean `False` and returns all data. Am I right?

**Comment by collerek** [comment]
> > **Describe the bug** Not applying Zero(0) size `limit`.
> > **To Reproduce**
> > ```python
> > >>> await User.objects.limit(0).all()
> > [User({}), ...]  # list of all users
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Expected behavior** I expected an empty list to be returned.
> > **Versions:**
> > 
> > * Database backend: PostgreSQL
> > * Python version: 3.10.4
> > * `ormar` version: 0.11.2
> > * `pydantic`: 1.9.0
> 
> I guess it doesn't apply because zero is boolean `False` and returns all data. Am I right?

Yep, that's in the Query class there is a check for `if self.limit_count` somewhere.

**Comment by SepehrBazyar** [comment]
> > > **Describe the bug** Not applying Zero(0) size `limit`.
> > > **To Reproduce**
> > > ```python
> > > >>> await User.objects.limit(0).all()
> > > [User({}), ...]  # list of all users
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Expected behavior** I expected an empty list to be returned.
> > > **Versions:**
> > > 
> > > * Database backend: PostgreSQL
> > > * Python version: 3.10.4
> > > * `ormar` version: 0.11.2
> > > * `pydantic`: 1.9.0
> > 
> > 
> > I guess it doesn't apply because zero is boolean `False` and returns all data. Am I right?
> 
> Yep, that's in the Query class there is a check for `if self.limit_count` somewhere.

OK thanks
I will fix it.
