### ISSUE TITLE
Improve filtering by date

### ISSUE THREAD

**Issue by CL545740896** [collerek/ormar#79]
How to filter by date

**Comment by CL545740896** [comment]
"Don't know how to literal-quote value datetime.date(2020, 12, 20)"
await CrawlLog.objects.filter(created_at=datetime.today().date()).all()

**Comment by collerek** [comment]
Hi, it should work like you posted, you can pass `datetime.date()` with a date set, for most of backend you should also be able to pass string like "2020-12-20" and should work. But if you selected a DateTime column remember that you have time there also and if you do not provide one automatically in your date midnight time (00:00:00) is added.

Then you need to use range like `filter(created_at__lt=DateTime.date(), created_at__gt=datetime.date())` and select midnight time of today and next day. To see what operands are available check filter documentation in docs.

If you want more specific response please post your model and example usage you want to achieve.

**Comment by zdytch** [comment]
I get the same exception

The model field:
`updated_at: datetime = ormar.DateTime()`

Filter:
`await Indicator.objects.filter(updated_at__lt=datetime(2021, 5, 19, 0, 0, 0, 0)).all()`

Exception:
`NotImplementedError: Don't know how to literal-quote value datetime.datetime(2021, 5, 19, 0, 0)`

**Comment by zdytch** [comment]
Current workaround is to convert datetime to string with the same format used in DB:

```
dt = datetime(2021, 5, 19, 0, 0, 0, 0).strftime("%Y-%m-%d %H:%M:%S")
await Indicator.objects.filter(updated_at__lt=dt).all()
```

**Comment by collerek** [comment]
If you set the date manually you can even use the string straight away like `await Indicator.objects.filter(updated_at__lt='2021-05-19').all()`.

Can you post like full example (with sample model and sample data) that fails that I can include in the tests?

You use postgres?

**Comment by zdytch** [comment]
Yes, I use postgres

Model:
```
class SampleModel(ormar.Model):
    id: int = ormar.Integer(primary_key=True)
    updated_at: datetime = ormar.DateTime()
```

Code that fails:
```
from datetime import datetime

creation_dt = datetime(2021, 5, 18, 0, 0, 0, 0)
sample = await SampleModel.objects.create(updated_at=creation_dt)

current_dt = datetime(2021, 5, 19, 0, 0, 0, 0)
outdated_samples = await SampleModel.objects.filter(updated_at__lt=current_dt).all()
```

**Comment by collerek** [comment]
Added in 0.10.14 (via #265).
Please update and check.

**Comment by zdytch** [comment]
@collerek 
It works now without converting to string. Thank you!
