### ISSUE TITLE
PostgresSyntaxError when save_related() pk only model

### ISSUE THREAD

**Issue by Dezorgon** [collerek/ormar#812]
**Describe the bug**

Have such models
```
class A(ormar.Model):
    class Meta(BaseMeta):
        pass

    id = ormar.Integer(primary_key=True)


class B(ormar.Model):
    class Meta(BaseMeta):
        pass

    id = ormar.Integer(primary_key=True)
    a = ormar.ForeignKey(A)
```

Trying to save an instance along with the related
```
a = A(data)
await a.save()
await a.save_related(follow=True, save_all=True)
```
Get an error
```
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "WHERE"
```

![image](https://user-images.githubusercontent.com/62138143/188513862-edb7cf81-8e6c-47cb-9a17-7a09927a142b.png)
Due to empty _self_fields_, the sql request is generated incorrectly
https://github.com/collerek/ormar/blob/db06d434e6bb7de5756caf9ea8943b279c809b36/ormar/models/model.py#L238

**Versions:**
 - Database backend used: postgress
 - Python version: 3.9
 - `ormar` version: 0.11.2
 - `pydantic` version: 1.9.1
 - if applicable `fastapi` version: 0.81.0

**Comment by collerek** [comment]
Can you provide a snippet to reproduce (i.e. what is your data where you define the related models)?
