### ISSUE TITLE
New CheckColumns constraint code change breaks usage of `PrimaryKeyConstraint`

### ISSUE THREAD

**Issue by zevisert** [collerek/ormar#821]
If this is the case why not use `issubclass(target_class, ColumnCollectionMixin)`?

_Originally posted by @zevisert in https://github.com/collerek/ormar/pull/730#discussion_r965487219_

**Comment by zevisert** [comment]
I'm manually using `PrimaryKeyConstraint` to create tables with composite foreign keys. I'm aware of #137, and would like to come up with a PR for it, but until now things were working fine.

**Comment by collerek** [comment]
The `PrimaryKeyConstraint` does not work in relations, so you use it only in the "main/parent" models? A dirty fix would be to add also pk constraint to constructors in the place you commented.

**Comment by zevisert** [comment]
Sorry, I meant composite primary keys - we're just using it in `meta.constraints`  to override the primary key. We also use `ForeignKeyConstraint` in a similar way to create composite foreign keys, but that's not the issue here. I'll spend today working on #137 - we use ormar heavily enough, it'd be good to contribute back to it - then we can remove some of the workarounds we have internally too

**Comment by collerek** [comment]
#137 That is quite complex and big task. There is a branch composite_pks that implements most of the logic and most of the tests but it's not finished

**Comment by zevisert** [comment]
Yeah, I keep coming back to read it quite frequently.. Definitely a lot of work, but maybe I can make some progress on it. I've got a branch going based on 0.11.3 with @tillspeicher's tests cherry-picked on it plus a few of my changes around how `Model.pk` and `pkname` works. I didn't notice the composite_pks branch, I'll take a look at that - thanks

**Comment by collerek** [comment]
There is a suboptimal design where fileds declaration is kept in dictionary as you can have different alias and real db name, that should be a class that is storing this info. Cause you can filter, order etc by those related models using those aliases but in queries they need to be resolved to actual db names with prefixes ( to make it more complicated😅)

**Comment by zevisert** [comment]
I see some of that. What's the best way forward here - should I be attempting anew (pulling some ideas from the `composite_pks` branch), or should I be contributing to work that's already complete on that branch? Is this TODO list the most organized one we have?

https://github.com/collerek/ormar/blob/810b13bcb756a07b10df344f7a0d2e61f05aaa75/tests/test_model_definition/pks_and_fks/test_composite_pks_and_fks.py#L962-L1003
