### ISSUE TITLE
Possibility for multitenancy / 'set search path' support for postgres?

### ISSUE THREAD

**Issue by bharling** [collerek/ormar#83]
Looked through the docs and the source for any way to handle this but I couldn't see anything as such.

Is it possible to implement multi-tenant schemas along the lines of the alembic example in their cookbook?

https://alembic.sqlalchemy.org/en/latest/cookbook.html

Essentially I guess we'd need a way to obtain a reference to the active db connection and execute `set search path ...` with some parameter ( ideally in the context of fastapi this would be a dependency ).

Secondly it would require a way to pass `__table_args__` in the Meta class definition for a Model.

Happy to have a stab at a PR for this if someone could point me at where to start, or even if there is a way to obtain a ref to the connection in a given context that would probably get me a long way towards what i need 

many thanks for this ORM by the way, have hunted high and low for a decent async ORM for FastAPI and this is really impressive.

**Comment by collerek** [comment]
`__table_args__` in Meta refers to `sqlalchemy.orm` which is not used in `ormar`.

During creation of `sqlalchemy.core` Tables `ormar` do not specify `schema` so by default it should be `None` so ok for `alembic` purposes, unless you specify default schema in `metadata` used during model declaration. So for `alembic` migration you should be good to go. (don't have to explicitly nullify the schema if by default it's not set)

As for the connection each model keeps the `database` reference in models `Meta` class, which is an instance of `Database` from `encode/databases`. You can get `connection()` from there and you need to use the same instance to connect/disconnect with `fastapi` so by the time you reach your code it should already be connected (i.e. in startup event as in `starlette`). 

But you don't even need the underlying connection, you can execute a query straight as `database.execute(query)`, you can check internals of databases and your backend in their package.

**Comment by collerek** [comment]
Hope that helps you out, gonna close it for now.
