### ISSUE TITLE
Enum Support

### ISSUE THREAD

**Issue by jbertman** [collerek/ormar#85]
Does Ormar natively support sqlalchemy enums and the Pydantic counterparts?

Something like:
```python
class ThingType(str, Enum):
    ONE = "ONE"
    TWO = "TWO"
    THREE = "THREE"

class Thing(BaseModel):
    class Meta(ormar.ModelMeta):
        tablename = "things"

    thing_type: ThingType = ormar.StringEnum(
        ThingType,
        default=ThingType.ONE
    )
```

They're nicely validated by FastAPI + Pydantic, I'd imagine in the meantime you could create the inputs yourself, but Ormar seems tooled around reducing work, so I think it'd be a cool feature if it doesn't exist already.

EDIT: I noticed the choices array (can be inserted as `choices=list(ThingType)` above), which validates during database processing, but I'm hoping we can bubble it up to Pydantic.

**Comment by collerek** [comment]
Actually it's the other way around. It's used in pydantic only, but since you cannot set the value on `ormar` model you cannot save it in database thorough ormar.

Choices adds pydantic validator to the model and that's why it should work with fastapi too (don't remember if tested this specifically).

**Comment by jbertman** [comment]
AFAICT, I don't see the enum options in FastAPI's OpenAPI spec when I provide a choices list. The choices validator does fire after submitting a payload. It's also possible I'm just using it wrong - do you happen to have a working case with FastAPI? 

Making use of Pydantic enums fed to FastAPI does a good job of informing the frontend of available options. So it would be really great to have this as feature.

**Comment by collerek** [comment]
Ah, yeah forgot about the schema, will check how to add this info with choices and if/how support enum field. Thanks for the idea!

**Comment by collerek** [comment]
Added in 0.9.1 with #93

As for now `choices` appear in schema and in OpenApi schema - it's easier than defining all variants of `Enums` (depending on the field type) and it's more intuitive to use in my opinion. 

You can always use `Enum` and pass it to choices as you already described. Updated the docs in this regard.

`choices` use the same schema options as actual `Enum` so should be intuitive and easy to use by API consumers in `fastapi`.
