### ISSUE TITLE
save_related doesn't work if id is uuid

### ISSUE THREAD

**Issue by eloi-martinez-qida** [collerek/ormar#885]
**Describe the bug**
If you use Model.save_related and the model has a uuid pk instead of an int it doent save anything
(The save itself returns the numer of rows saved correctly)

**To Reproduce**
Copy code example of https://collerek.github.io/ormar/models/methods/#save_related
Code works as expected.
replace id with `id: UUID4 = ormar.UUID(primary_key=True, default=uuid4)`
Now the get() raises `ormar.exceptions.NoMatch`

**Expected behavior**
Expect the same behavior as with int pk.

**Versions (please complete the following information):**
 - Database backend used postgress
 - Python version python:3.10.8-slim-bullseye (docker image)
 - `ormar` version 0.11.3
 - `pydantic` version 1.10.2
 - if applicable `fastapi` version 0.85.0

**Comment by collerek** [comment]
Fixed in 0.12.0, please update and check.
