### ISSUE TITLE
FastAPI Users/ormar integration

### ISSUE THREAD

**Issue by paolodina** [collerek/ormar#91]
Reference: https://github.com/collerek/ormar/issues/84#issuecomment-769040069
> If you feel like it you can try on your own with FastapiUsers, I can help if you get stuck on the way :)

Yep, I'd be interested in doing that and thought to open this ticket to avoid that you or someone else also work on this at the same time.

I had a look at FastAPI Users code and I have to say that ormar/fastapi users integration shouldn't be too hard.
Basically they have the concept of "adapter", and the code for already implemented adapters is available [here](https://github.com/paolodina/fastapi-users/tree/master/fastapi_users/db). Being able to provide the ormar adapter should do the trick, and for that I can take the [Tortoise adapter](https://github.com/paolodina/fastapi-users/blob/master/fastapi_users/db/tortoise.py) as a starting point.

I hope to be able to finish the integration without issues and I'll keep this ticket updated when something will happen, in case of problems I accept your offer to help. I'll anyway refer to you @collerek for proofreading.

Thanks!

**Comment by collerek** [comment]
I looked quite some time ago into the fastapiusers and one trick point might be that it uses some template pydantic models to parse db models (at least that's what I remember, might have changed). 

The trick is that ormar models **are** pydantic models so maybe you can skip the whole parsing in users but didn't dig deeper so hard to tell if this is really possible.

**Comment by paolodina** [comment]
Ok, I got something.

There is the FastAPI Users fork ([branch](https://github.com/paolodina/fastapi-users/tree/ormar), [commit](https://github.com/paolodina/fastapi-users/commit/f77d6b0073e296d21f1b3b5845a05cb3f1c26c94)) and [here](https://github.com/paolodina/fastapi-users-ormar-demo) a the demo anyone can try and report back in case of problems.

Currently I tested only the `/auth/` and `/users` endpoint, it seems working so far. I still have to test other endpoints and implement the oauth user case.

I'd appreciate if you could have a look at the code on the fork (basically [it's only one file](https://github.com/paolodina/fastapi-users/blob/f77d6b0073e296d21f1b3b5845a05cb3f1c26c94/fastapi_users/db/ormar.py) containing the implementation), it's commented with some question/consideration.

About this
> The trick is that ormar models are pydantic models so maybe you can skip the whole parsing in users but didn't dig deeper so hard to tell if this is really possible.

I don't know if my code is OK but I didn't find any tricky part.

**Comment by collerek** [comment]
Created a pull request https://github.com/paolodina/fastapi-users/pull/1 with finished ormar db backend, with all power features of ormar used :)

Please review this and let me know what you think. 
In my opinion what is left is more tests and documentation update but again didn't dig deep into fastapi-users and never used it. 

As for the "tricky" part my idea was that maybe you can skip parsing to dict and recreating fastapi-users models but i think its imposible.

Run black and flake8 on the code but didn't run mypy, so it's also to be checked (if fastapi-users uses it).

**Comment by collerek** [comment]
@paolodina the PR is merged! 
Good job and thanks ;)

If you have other `fastapi` ecosystem libraries that you would like `ormar` to support let me know, we can work this out ;)
