### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by alexol91** [collerek/ormar#993]
When my application throws an exception and I try to access an endpoint again, it returns the error "**(2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')"**.

It is as if it were not connected to the database or as if it did not refresh. Using SQLAlchemist I edited the parameters "**pool_timeout=60, pool_recycle=280, pool_size=20, max_overflow=50**" when I call create_engine, but in ORMAR I don't know how to do it.

Any idea how to do it?

Thanks!

**Comment by collerek** [comment]
That will be on the databases side: https://www.encode.io/databases/connections_and_transactions/

The actual values depend on the backend used

I.e. for Mysql, you can pass values accepted by aiomysql: https://github.com/encode/databases/blob/b6eba5f7a19eaf8966e3821f44fe00f4770cb822/databases/backends/mysql.py#L36-L74
